check stdout in validate job

diff --git a/.github/workflows/selftest.yml b/.github/workflows/selftest.yml
--- a/.github/workflows/selftest.yml
+++ b/.github/workflows/selftest.yml
@@ -14,17 +14,7 @@ jobs:
         - name: Clone this repository
           uses: actions/checkout@v2
         - name: Test without any input arguments
-          id: test1
           uses: ./
-        - name: Check stdout
-          run: |
-            if [[ "${{ steps.test1.outputs.stdout }}" == *"Citation metadata are valid"* ]]; then
-                echo "Success"
-                # exit 0
-            else
-                echo "Failed"          
-                # exit 1
-            fi       
 
   show-help:
       runs-on: ubuntu-latest
@@ -52,10 +42,20 @@ jobs:
         - name: Clone this repository
           uses: actions/checkout@v2
         - name: Validate a CITATION.cff file from the current directory
+          id: step_validate
           uses: ./
           with:
             args: --validate
-  
+        - name: Check stdout
+          run: |
+            if [[ "${{ steps.step_validate.outputs.stdout }}" == *"Citation metadata are valid"* ]]; then
+                echo "Success"
+                # exit 0
+            else
+                echo "Failed"          
+                # exit 1
+            fi         
+
   subdirectory:
       runs-on: ubuntu-latest
       steps:
